name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-fole: package.json

      - name: Install Dependencies
        run: npm i

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          publish: |
            npm run build &&
            zip -r boil-node-22.zip dist/boil.cjs -j &&
            gh release upload ${{github.event.release.tag_name}} boil-node-22.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
