name: Release & Publish

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  version-and-tag:
    name: Version & Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      published: ${{ steps.publish-output.outputs.published }}
      publishedPackages: ${{ steps.publish-output.outputs.publishedPackages }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install Dependencies
        run: npm ci

      - name: Version Packages & Create Tags
        id: changesets
        uses: changesets/action@v1
        with:
          version: npx changeset version
          publish: npx changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Job Outputs
        id: publish-output
        run: |
          # Workaround: intermediate variable prevents shell quoting issues
          # that interfere with fromJson deserialization
          publishedPackages=${{ toJSON(steps.changesets.outputs.publishedPackages) }}

          echo 'published=${{ steps.changesets.outputs.published }}' >> "$GITHUB_OUTPUT"
          echo "publishedPackages=$publishedPackages" >> "$GITHUB_OUTPUT"

  create-releases:
    name: Create GitHub Releases
    needs: [version-and-tag]
    if: needs.version-and-tag.outputs.published == 'true'
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        package: ${{ fromJson(needs.version-and-tag.outputs.publishedPackages) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Package & Create Release
        run: |
          npm run build

          tar czf ./dist/boil-node-22.tgz ./dist/boil.cjs

          tag="${{ matrix.package.name }}@${{ matrix.package.version }}"
          gh release create "$tag" ./dist/*.tgz \
            --repo="$GITHUB_REPOSITORY" \
            --title="$tag" \
            --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
